use googleuuid.Parse instead of regex for parsing uuids
promoboxx/go-service pull request #23
Opened 2021-05-10 21:00 UTC by gudetimes1234

2021-05-10 21:06 UTC, gudetimes1234 commented
Looks like tests are failing because Circle isn't able to spin up the environment

2021-05-10 22:25 UTC, tsharkey commented on uuid/validate.go
> +	return isValid
You can make this a little shorter and just do `return err == nil`

2021-05-13 15:39 UTC, tsharkey commented
Just noticed that we don't have any tests for this stuff either. Can you add some tests for this function as well please

2021-05-18 14:47 UTC, tsharkey requested changes

2021-05-18 14:47 UTC, tsharkey commented on uuid/validate_test.go
> +func TestIsValid(t *testing.T) {
For our test names we try to prefix them with what type of test they are. So in this case `TestUnit_IsValid`. We do this so we can filter tests when running them from our Makefiles. Like just trying to run Unit tests you can do `go test -r Unit` and then all the unit tests run. 
```suggestion
func TestUnit_IsValid(t *testing.T) {
```

2021-05-20 14:53 UTC, tsharkey approved these changes

2021-05-20 19:20 UTC, merged